// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: activity.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ActivityLogClient is the client API for ActivityLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityLogClient interface {
	Insert(ctx context.Context, in *Activity, opts ...grpc.CallOption) (*InsertResponse, error)
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*Activity, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*Activities, error)
}

type activityLogClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityLogClient(cc grpc.ClientConnInterface) ActivityLogClient {
	return &activityLogClient{cc}
}

func (c *activityLogClient) Insert(ctx context.Context, in *Activity, opts ...grpc.CallOption) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, "/api.v1.ActivityLog/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityLogClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*Activity, error) {
	out := new(Activity)
	err := c.cc.Invoke(ctx, "/api.v1.ActivityLog/Retrieve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityLogClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*Activities, error) {
	out := new(Activities)
	err := c.cc.Invoke(ctx, "/api.v1.ActivityLog/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityLogServer is the server API for ActivityLog service.
// All implementations must embed UnimplementedActivityLogServer
// for forward compatibility
type ActivityLogServer interface {
	Insert(context.Context, *Activity) (*InsertResponse, error)
	Retrieve(context.Context, *RetrieveRequest) (*Activity, error)
	List(context.Context, *ListRequest) (*Activities, error)
	mustEmbedUnimplementedActivityLogServer()
}

// UnimplementedActivityLogServer must be embedded to have forward compatible implementations.
type UnimplementedActivityLogServer struct {
}

func (UnimplementedActivityLogServer) Insert(context.Context, *Activity) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedActivityLogServer) Retrieve(context.Context, *RetrieveRequest) (*Activity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedActivityLogServer) List(context.Context, *ListRequest) (*Activities, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedActivityLogServer) mustEmbedUnimplementedActivityLogServer() {}

// UnsafeActivityLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityLogServer will
// result in compilation errors.
type UnsafeActivityLogServer interface {
	mustEmbedUnimplementedActivityLogServer()
}

func RegisterActivityLogServer(s grpc.ServiceRegistrar, srv ActivityLogServer) {
	s.RegisterService(&ActivityLog_ServiceDesc, srv)
}

func _ActivityLog_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Activity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityLogServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.ActivityLog/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityLogServer).Insert(ctx, req.(*Activity))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityLog_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityLogServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.ActivityLog/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityLogServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityLog_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityLogServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.ActivityLog/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityLogServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivityLog_ServiceDesc is the grpc.ServiceDesc for ActivityLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivityLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.ActivityLog",
	HandlerType: (*ActivityLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _ActivityLog_Insert_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _ActivityLog_Retrieve_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ActivityLog_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity.proto",
}
